name: .NET General Workflow

on:
  push:
    branches: [ isolinebranch ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install Dependencies and Packages
      run: |
        dotnet restore
        dotnet tool install -g dotnet-format

    - name: Build and Test
      working-directory: ./IsolinesProj
      run: |
        dotnet build --no-restore --configuration Release
        dotnet test --no-build --verbosity normal

    # Optional: Statiq installation removed if package is not available
    # - name: Install Statiq CLI
    #   run: dotnet tool install -g Statiq.Web

    # Optional: Documentation generation removed if Statiq is not available
    # - name: Generate Documentation
    #   working-directory: ./IsolinesProj
    #   run: |
    #     export PATH="$PATH:~/.dotnet/tools"
    #     statiq build --input . --output site

    - name: Update README.md with Documentation
      run: |
        echo "<!-- Generated Documentation -->" > README.md
        cat site/index.html >> README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        git push
