name: .NET General Workflow

on:
  push:
    branches: [ isolinebranch ]  # Der Workflow wird ausgeführt, wenn auf diesen Branch gepusht wird.
  pull_request:
    branches: [ main ]  # Der Workflow wird ausgeführt, wenn ein Pull Request zu diesem Branch geöffnet oder aktualisiert wird.

jobs:
  build:
    runs-on: windows-latest  # Da dein Build auf Windows besser funktioniert

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      working-directory: ./IsolinesProj
      run: dotnet restore

    - name: Build and Test
      working-directory: ./IsolinesProj
      run: |
        dotnet build --no-restore --configuration Release
        dotnet test --no-build --verbosity normal

    - name: Install Statiq CLI
      run: dotnet tool install -g Statiq.Web

    - name: Generate Documentation
      working-directory: ./IsolinesProj
      run: |
        export PATH="$PATH:~/.dotnet/tools"
        statiq build --input . --output site

    - name: Update README.md with Documentation
      run: |
        echo "<!-- Generated Documentation -->" > README.md
        cat IsolinesProj/site/index.html >> README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        git push
