name: .NET General Workflow 2

on:
  push:
    branches: [verticalgradientbranch]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }} 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore VerticalGradient/VerticalGradient.sln

    - name: Add Statiq.Web.GitHub Package
      run: dotnet add VerticalGradient/VerticalGradient.csproj package Statiq.Web.GitHub --version 1.0.0-beta.60

    - name: Build Main Solution
      run: dotnet build VerticalGradient/VerticalGradient.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestVerticalGradient/TestVerticalGradient.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test VerticalGradient/VerticalGradient.sln --configuration Release --verbosity normal

    - name: Generate Documentation
      run: |
        cd VerticalGradient
        # Run Statiq build
        dotnet run --project VerticalGradient.csproj -- statiq build --config statiq.config || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly configured."

    - name: Update README.md with Documentation
      run: |
        # Ensure we are in the root directory
        cd ${{ github.workspace }}
        echo "<!-- Generated Documentation -->" > README.md
        # Append the generated documentation content from the VerticalGradient directory
        if [ -f VerticalGradient/README.md ]; then
          cat VerticalGradient/README.md >> README.md
        else
          echo "README.md in VerticalGradient not found." >> README.md
        fi
        
    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        git push
