name: .NET General Workflow 2

on:
  push:
    branches: [verticalgradientbranch]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }} 

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore VerticalGradient/VerticalGradient.sln

    - name: Add Statiq.Web.GitHub Package
      run: dotnet add VerticalGradient/VerticalGradient.csproj package Statiq.Web.GitHub --version 1.0.0-beta.60

    - name: Build Main Solution
      run: dotnet build VerticalGradient/VerticalGradient.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestVerticalGradient/TestVerticalGradient.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test VerticalGradient/VerticalGradient.sln --configuration Release --verbosity normal

    # Optional: Environment Check
    - name: Check Environment Variables
      run: |
        Write-Output "DOTNET_ROOT: $env:DOTNET_ROOT"
        Write-Output "Current Directory: $(Get-Location)"
      shell: pwsh
