name: .NET General Workflow

on:
  push:
    branches: [isolinebranch]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore IsolinesProj/IsolinesProj.sln

    - name: Build Main Solution
      run: dotnet build IsolinesProj/IsolinesProj.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestProjectIsoline/TestProjectIsoline.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal

    # Optional: Environment Check
    - name: Check Environment Variables
      run: |
        Write-Output "DOTNET_ROOT: $env:DOTNET_ROOT"
        Write-Output "Current Directory: $(Get-Location)"
      shell: pwsh
