name: .NET General Workflow

on:
  push:
    branches: [isonlinebranch]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to latest version

    - name: Setup .NET
      uses: actions/setup-dotnet@v3  # Update to latest version
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore IsolinesProj/IsolinesProj.sln

    - name: Build Main Solution
      run: dotnet build IsolinesProj/IsolinesProj.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestProjectIsoline/TestProjectIsoline.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal

    - name: Generate Documentation
      run: |
        cd IsolinesProj
        dotnet statiq build --config Statiq.config || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly configured."

    - name: Update README.md with Documentation
      run: |
        echo "<!-- Generated Documentation -->" > README.md
        cat IsolinesProj/site/index.html >> README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        git push
