name: .NET General Workflow

on:
  push:
    branches: [ isonlinebranch ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore IsolinesProj/IsolinesProj.sln

    - name: Add Statiq.Web.GitHub Package
      run: dotnet add package Statiq.Web.GitHub --version 1.0.0-beta.60

    - name: Build Main Solution
      run: dotnet build IsolinesProj/IsolinesProj.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestProjectIsoline/TestProjectIsoline.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal

    - name: Generate Documentation
      run: |
        cd IsolinesProj
        statiq build --input . --output site || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly installed."

    - name: Update README.md with Documentation
      run: |
        echo "<!-- Generated Documentation -->" > README.md
        cat IsolinesProj/site/index.html >> README.md

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        git push
