name: .NET General Workflow

on:
  push:
    branches: [isolinebranch]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}  # Ensure we are on the correct branch

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore IsolinesProj/IsolinesProj.sln

    - name: Add Statiq.Web.GitHub Package
      run: dotnet add IsolinesProj/IsolinesProj.csproj package Statiq.Web.GitHub --version 1.0.0-beta.60

    - name: Build Main Solution
      run: dotnet build IsolinesProj/IsolinesProj.sln --no-restore --configuration Release

    - name: Build Test Project
      run: dotnet build TestProjectIsoline/TestProjectIsoline.csproj --no-restore --configuration Release

    - name: Test Projects
      run: dotnet test IsolinesProj/IsolinesProj.sln --configuration Release --verbosity normal

    - name: Generate Documentation
      run: |
        cd IsolinesProj
        # Run Statiq build
        dotnet run --project IsolinesProj.csproj -- statiq build --config statiq.config || echo "Statiq build failed. Check if Statiq.Web.GitHub is correctly configured."

    - name: Update README.md with Documentation
      run: |
        echo "<!-- Generated Documentation -->" > README.md
        # Check if the site directory and index.html exist
        if (Test-Path IsolinesProj/site/index.html) {
          cat IsolinesProj/site/index.html >> README.md
        } else {
          echo "index.html not found." >> README.md
        }

    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README.md with generated documentation" || echo "No changes to commit"
        # Push changes using the GITHUB_TOKEN for authentication
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
